package com.example.ttlock.model;

/**
 * Created by Administrator on 2016/9/6 0006.
 */
public class KeyObj {

    /**
     * ekey type:110301-admin ekey, 110302-common user ekey
     */
    public String userType;

    /**
     * key status
     * "110401"	Normal use
     * "110402"	To be received
     * "110405"	Frozen
     * "110408"	deleted
     * "110410"	Reset
     */
    public String keyStatus;

    /**
     * lock id
     */
    public int lockId;

    /**
     * key id
     */
    public int keyId;


    /**
     * lock version information(json format)
     */
    public LockVersionObj lockVersion;

    /**
     * lock name
     */
    public String lockName;

    /**
     * lock alias
     */
    public String lockAlias;

    /**
     * lock mac
     */
    public String lockMac;

    /**
     * battery
     */
    public int electricQuantity;

    /**
     * lock flag position
     */
    public int lockFlagPos;

    /**
     *  admin code, which only belongs to the admin ekey, will be used to verify the admin permission.
     *
     */
    public String adminPwd;

    /**
     * The key data which will be used to unlock
     */
    public String lockKey;

    /**
     * Super passcode, which only belongs to the admin ekey, can be entered on the keypad to unlock
     */
    public String noKeyPwd;

    /**
     * Erasing passcode,which belongs to old locks, has been abandoned. Please don't use it.
     */
    public String deletePwd;

    /**
     * Initial data of passcode, which is generated by SDK, is used to create passcode
     */
    public String pwdInfo;

    /**
     * The timestamp which is generated by SDK during lock initializing time
     */
    public long timestamp;

    /**
     * aesKey
     */
    public String aesKeyStr;

    /**
     * The time when it becomes valid
     */
    public long startDate;

    /**
     * The time when it is expired
     */
    public long endDate;

    /**
     * characteristic value. it is used to indicate what kinds of feature do a lock support.
     */
    public int specialValue;

    /**
     * The offset between your time zone and UTC, in millisecond
     */
    public int timezoneRawOffset;

    /**
     * Is key authorized:0-NO,1-yes
     */
    public int keyRight;

    /**
     * Passcode version: 0、1、2、3、4
     */
    public int keyboardPwdVersion;

    /**
     * is support remote unlock: 1 - yes 、 2 - no
     */
    public int remoteEnable;

    /**
     * Comment
     */
    public String remarks;

    /**
     * Product model
     */
    public String modelNum;

    /**
     * Hardware version
     */
    public String hardwareRevision;

    /**
     * Firmware version
     */
    public String firmwareRevision;

}
